version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  # Spring Boot Application
  app:
    image: anaumovich26/springboot-docker-internship:latest
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      DEVOPS: Anna
    ports:
      - "8081-8085:8080"
    deploy:
      replicas: 5

  web:
    image: anaumovich26/nginx_lb:latest
    depends_on:
      - app
    ports:
      - "8080:80"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8086:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  db_data:
  jenkins_home:
