name: Lint GitHub Actions
on:
  pull_request:
  workflow_dispatch:
jobs:
  MavenBuildAndLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '17'
      - run: ls -a .
        name: List current directory
      - run: mvn clean compile
        name: Build project
      - run: mvn checkstyle:check spotbugs:check org.owasp:dependency-check-maven:check
        name: Run Checkstyle
      - uses: actions/upload-artifact@v4
        name: "Publish build artifacts"
        if: always()
        with:
          path: '**/target/*.jar'
